name: agroconecta
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  dio: ^5.9.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^3.0.3
  flutter_svg: ^2.0.9
  formz: ^0.8.0
  go_router: ^16.2.5
  google_fonts: ^6.3.2
  intl: ^0.20.2
  table_calendar: ^3.2.0
  url_launcher: ^6.3.0
  awesome_notifications: ^0.10.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/banners/
    - assets/icons/
    - google_fonts/montserrat_alternates/
