export 'email.dart';
export 'password.dart';
export 'phone_number.dart';
export 'confirmed_password.dart';
export 'name.dart';
export 'lastname.dart';
export 'curp.dart';
export 'date_of_birth.dart';
export 'terms.dart';
